#!/usr/bin/env python3
"""
Safe, limited replacer for webui/static/app.js for batch-1.

It performs conservative conversions only:
 - If an element already has data-action and also has an onclick attribute, move the onclick value to data-old-onclick and remove onclick.
 - If a button has onclick calling document.getElementById('fileInput').click(), replace that onclick with data-action="upload-files" and data-old-onclick containing the original call.

The script writes a timestamped backup if it modifies the file.
"""
import re
from pathlib import Path
from datetime import datetime
import shutil

TARGET = Path('webui/static/app.js')


def backup(p: Path):
    ts = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    bak_dir = Path('backups/frontend')
    bak_dir.mkdir(parents=True, exist_ok=True)
    bak = bak_dir / (p.name + f'.bak.{ts}')
    shutil.copy2(p, bak)
    return bak


def main():
    if not TARGET.exists():
        print(f'Missing {TARGET}; abort')
        return
    txt = TARGET.read_text(encoding='utf8')
    orig = txt

    # 1) data-action="..." onclick="..."  (double-quote)
    def repl_da_double(m):
        da = m.group(1)
        onclick = m.group(2)
        # if data-old-onclick already exists in the matched snippet, skip
        if 'data-old-onclick=' in m.group(0):
            return m.group(0)
        # produce attribute list: keep data-action, add data-old-onclick
        onclick_esc = onclick.replace('"', '\\"')
        return f'{da} data-old-onclick="{onclick_esc}"'

    txt = re.sub(r'(data-action="[^"]+")\s+onclick="([^"]+)"', repl_da_double, txt)

    # 1b) data-action='...' onclick='...' (single-quote)
    def repl_da_single(m):
        da = m.group(1)
        onclick = m.group(2)
        if "data-old-onclick=" in m.group(0):
            return m.group(0)
        onclick_esc = onclick.replace("'", "\\'")
        return f"{da} data-old-onclick='{onclick_esc}'"

    txt = re.sub(r"(data-action='[^']+')\s+onclick='([^']+)'", repl_da_single, txt)

    # 2) button onclick that triggers file input click -> add data-action and data-old-onclick
    # handle common quoting variants
    patterns = [
        r'onclick="document\.getElementById\(\'fileInput\'\)\.click\(\)"',
        r"onclick='document\.getElementById\(\"fileInput\"\)\.click\(\)'",
    ]

    for pat in patterns:
        # replace occurrences of e.g. <button ... onclick="document.getElementById('fileInput').click()" ...>
        def _repl(m):
            before = m.group(1) or ''
            after = m.group(2) or ''
            # If data-action already present, skip
            if 'data-action=' in before + after:
                return m.group(0)
            return f'<button data-action="upload-files" data-old-onclick="document.getElementById(\'fileInput\').click()"{before}{after}>'

        txt = re.sub(rf'<button([^>]*)({pat})([^>]*)>', _repl, txt)

    # 3) file action buttons generated by template strings calling rptUI methods
    #    e.g. onclick="rptUI.selectAndAnalyzeFile('${filename}')"
    # We conservatively handle single-argument calls that use a template var like ${filename}
    def camel_to_kebab(name: str) -> str:
        s1 = re.sub('([a-z0-9])([A-Z])', r'\1-\2', name)
        return s1.replace('_', '-').lower()

    def _repl_rptui(m):
        before = m.group(1) or ''
        method = m.group(2)
        var = m.group(3)
        after = m.group(4) or ''
        # If data-action already present, skip
        if 'data-action=' in before + after:
            return m.group(0)
        kebab = camel_to_kebab(method)
        # Keep original onclick in data-old-onclick; add data-action and data-arg-file (template var preserved)
        old = "rptUI.%s('${%s}')" % (method, var)
        # Need to escape quotes inside attribute
        old_esc = old.replace("'", "\\'")
        # Build return string carefully so ${var} remains as a literal template expression in the JS
        ret = "<button{} data-action=\"{}\" data-arg-file=\"${{{}}}\" data-old-onclick=\"{}\"{}>".format(before, kebab, var, old_esc, after)
        return ret

    txt = re.sub(r"<button([^>]*)onclick=\"rptUI\.([A-Za-z0-9_]+)\('\$\{([^}]+)\}'\)\"([^>]*)>", _repl_rptui, txt)

    # 4) Update querySelector/querySelectorAll selectors that look for onclick attributes
    #    e.g. document.querySelector('button[onclick="refreshFileListDebug()"]')
    # We conservatively add a fallback that looks for data-old-onclick containing the function name
    def _sel_repl_double(m):
        all_suffix = m.group(1) or ''
        func_call = m.group(2)
        # create a selector that prefers data-old-onclick (added by our replacements) then falls back to original
        sel_old = f"button[data-old-onclick*=\"{func_call.split('(')[0]}(\"]"
        orig = f"button[onclick=\"{func_call}\"]"
        return f"document.querySelector{all_suffix}('{sel_old}') || document.querySelector{all_suffix}('{orig}')"

    def _sel_repl_single(m):
        all_suffix = m.group(1) or ''
        func_call = m.group(2)
        sel_old = f"button[data-old-onclick*=\'{func_call.split('(')[0]}(\']" 
        orig = f"button[onclick=\'{func_call}\']"
        return f"document.querySelector{all_suffix}('{sel_old}') || document.querySelector{all_suffix}('{orig}')"

    txt = re.sub(r"document\.querySelector(All)?\(\'button\[onclick=\"([^\"]+)\"\]\'\)", _sel_repl_double, txt)
    txt = re.sub(r"document\.querySelector(All)?\(\"button\[onclick=\'([^\']+)\'\]\"\)", _sel_repl_single, txt)

    if txt != orig:
        bak = backup(TARGET)
        TARGET.write_text(txt, encoding='utf8')
        print(f'Wrote backup {bak} and updated {TARGET}')
    else:
        print(f'No changes needed for {TARGET}')


if __name__ == '__main__':
    main()
